version: '2.1'

services:
  mongodb:
    image: mongo:3.4.3
    ports:
      - "27020:27017"
    environment:
      SERVICE_IGNORE: 'true'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ['CMD-SHELL', 'echo "db.stats().ok" | mongo localhost/formioapp --quiet']
      interval: 5s
      timeout: 1s
      retries: 10
    networks:
      - mongodb
    logging:
      driver: none

  formio:
    image: "10.1.1.16:5020/formio:latest"
    env_file:
      - .env
    ports:
      - "8587:3001"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - formio_data:/data
    links:
      - mongodb
    networks:
      - mongodb
      - glinttcamundadocker_camunda-network

volumes:
  mongodb_data:
    driver: local
    driver_opts:
       type: none
       o: bind
       device: /data/camunda/GlinttFormio/dbfolder/mongodb_data
  formio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/camunda/GlinttFormio/dbfolder/formio_data

networks:
  mongodb:
    name: mongodb
    driver: bridge
  glinttcamundadocker_camunda-network:
    external: true